config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ActiveRecord::Base

  validates :image, presence: true

  has_attached_file :image, styles: { medium: "640x640" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    if @event = Event.create(event_params)
      flash[:success] = "Event created!"
      redirect_to events_path
    else
      flash[:alert] = "Failed to create event!"
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:success] = "Event updated!"
      redirect_to events_path
    end
      flash[:alert] = "Update failed!"
      render :edit
  end

  def destroy
    @event.destroy
    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit(:image, :title)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
.form-wrapper
  = simple_form_for @event, html: { class: 'form-horizontal', multipart: true } do |f|
    .form-group
      = f.input :image
    .form-group.text-center
      = f.input :title
    .form-group.text-center
      = f.button :submit, class: 'btn-success'

app/views/events/edit.html.haml
.text-center
  = image_tag @event.image.url(:medium)

= render 'form'

.text-center
  = link_to "Delete Event ", event_path(@event), method: :delete, data: { confirm: "Delete this event?" }
  |
  = link_to " Cancel", events_path

app/views/events/index.html.haml
.posts-wrapper.row
  -@events.each do |event|
    .post
      .post-head
        .name
          =event.title
      .post-body
        .row
          .col-md-3
            .left-block
              .image
                =link_to (image_tag event.image.url(:medium), class:'img-responsive'), event_path(event)
          .col-md-9
            .right-block
              .location
                Location: University of Colorado at Colorado Springs
              .time
                Time: October 4, 2016 @ 15:00
              .more-info
                This is a sample description made simply for demonstration purposes. Please ignore what the rest of this
                %br
                paragraph says for it actually is a waste of space.
                %br
                %br
                So long, and thanks for all the fish.
      .caption
        .row
          .col-md-9
          .col-md-1
            =link_to "Directions", '#'
          .col-md-1
            =link_to "Email Me", '#'
          .col-md-1
            =link_to "More Info", '#'

app/views/events/new.html.haml
= render 'form'
.text-center
  = link_to " Cancel", events_path

app/views/events/show.html.haml
.posts-wrapper.row
  .post
    .post-head
      .name
        Current Event
    .image.center-block
      =image_tag @event.image.url(:medium)
    %p.caption
      =@event.title
    .text-center
      =link_to "Cancel", events_path
      |
      = link_to "Edit Event", edit_event_path(@event)

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Alpha
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'


  #banner.container
    .row

  %body
    %nav.navbar.navbar-default
      .navbar-container
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle Navigation
            %span.icon-bar
            %span.icon-bar
          .navbar-brand= link_to "Home", root_path
        .collapse.navbar-collapse#bs-navbar-collapse-1
          %ul.nav.navbar-nav.navbar-left
            %li
              = link_to "Calendar", new_event_path
            %li
              = link_to "Map View", '#'
            %li
              = link_to "Happening Today", '#'
          %ul.nav.navbar-nav.navbar-right
            %form.navbar-form.navbar-left{:role => "search"}
              .form-grouo
                %input.form-control{:placeholder => "Search", :type => "text"}
                %button.btn.btn-default{:type => "submit"} Submit
  #wrapper
    #sidebar-wrapper
      .well.sidebar-nav
        %ul.nav-header Major Categories
        %ul.nav.nav-list
          %ui.nav-header Music
          %li
            = link_to "Concerts", '#'
          %li
            = link_to "Music Festivals", '#'
          %li
            = link_to "Orchestra", '#'
          %ui.nav-header Sports
          %li
            = link_to "Football", '#'
          %li
            = link_to "Baseball", '#'
          %li
            = link_to "Basketball", '#'
          %li
            = link_to "Soccer", '#'
          %ui.nav-header Art
          %li
            = link_to "Galleries", '#'
          %li
            = link_to "Theater", '#'
          %li
            = link_to "Dance", '#'
          %ui.nav-header Activities
          %li
            = link_to "Cycling", '#'
          %li
            = link_to "Running", '#'
          %li
            = link_to "Fund Raisers", '#'
          %li
            = link_to "For Kids", '#'
          %ui.nav-header Local
          %li
            = link_to "Festivals", '#'
          %li
            = link_to "Farmer's Market", '#'
          %lu.nav-header
            = link_to "Other", '#'
    #page-content-wrapper
      .page-content
        .container
          .row
            .col-md-12
              .container
                -flash.each do |name, msg|
                  = content_tag :div, msg, class: [:alert, alert_for(name)]
              = yield